---
title: "Online Books"
date: "`r Sys.Date()`"
author: Steven Wun
output:
  rmdformats::material:
    highlight: kate
  pdf_document: default
  word_document: default
  html_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Bioinformatics

## A Primer for Computational Biology

Book [website](https://open.oregonstate.education/computationalbiology/).

Copy this link: C:\\Library\\Bioinfo\\O\'Neil_APFCB

to the file explorer to access the book on the computer.


# Econometrics

## Introduction to Econometrics with R

***[Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html)*** by *Christoph Hanck, Martin Arnold, Alexander Gerber, and Martin Schmelzer*.


## Using R for Introductory Econometrics

[Using R for Introductory Econometrics](https://www.urfie.net/downloads/PDF/URfIE_web.pdf), 2020 (2nd edition), by _Florian Heiss_.

## Using Python for Introductory Econometrics

[Using Python for Introductory Econometrics](https://www.urfie.net/downloads/PDF/UPfIE_web.pdf), 2020 (1st edition), by _Florian Heiss_.

## Using Julia for Introductory Econometrics

[Using Julia for Introductory Econometrics](https://www.urfie.net/downloads/PDF/UJfIE_web.pdf), 2023 (1st edition), by _Florian Heiss_ and _Daniel Brunner_. 


The companion website for the above three books: https://www.urfie.net/

## The Effect

[The Effect](https://theeffectbook.net/index.html) by [Nick Huntington-Klein](https://www.nickchk.com/).



# Economics

## **Advanced Macroeconomics: An Easy Guide**
*By Filipe Campante, Federico Sturzenegger, Andrés Velasco*

The book was published on 11 October 2021 and can be accessed at this [link](https://press.lse.ac.uk/site/books/m/10.31389/lsepress.ame/).

PDF version of the book and some supplementary materials have been downloaded and were saved at the "Temporary_files" sub-folder of the "Library" folder.


## **Macroeconomic Policy**
*By Farrokh K. Langdana*

[Macroeconomic Policy: Demystifying Monetary and Fiscal Policy](https://mycuhk-my.sharepoint.com/:b:/g/personal/1005271920_link_cuhk_edu_hk/EV_3JSkA5-1IrAOZaylTVsIBLljRCOJeS9sb8EJ1n5T4AQ?email=andykhwun%40gmail.com&e=PRQswR) by *Farrokh K. Langdana*, 2022 (4th edition) contains many useful information like the definitions of inflation rate and GDP deflator and their difference.

You need password to access this book.

# Forecasting

## Forecasting: principles and practice, 3rd edition

This is the book website for the book ***[Forecasting: principles and practice, 3rd edition (2021)](https://otexts.com/fpp3/)*** by *Rob J Hyndman and George Athanasopoulos*. The book can be viewed online.

The author's website can be found [here](https://robjhyndman.com/).


# Julia

## Think Julia
[Think Julia: How to Think Like a Computer Scientist](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html) (2018) by _Ben Lauwens_ and _Allen Downey_.




# Machine Learning


## The Elements of Statistical Learning

[The Elements of Statistical Learning](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Machine-Learning/ESLII_print12_toc.pdf) (2009, 2nd Edition) by _Trevor Hastie_, _Robert Tibshirani_, and _Jerome Friedman_.

[Book Website](https://hastie.su.domains/ElemStatLearn/)

[Author's Website](https://hastie.su.domains/)

## An Introduction to Statistical Learning with Applications in Python

[An Introduction to Statistical Learning with Applications in Python](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Machine-Learning/ISLP_website.pdf) (2023, 1st Edition) by _Gareth James_, _Daniela Witten_, _Trevor Hastie_, _Robert Tishirani_, and _Jonathan Taylor_.

[Book Website](https://www.statlearning.com/)


## Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow, 2nd Edition

[Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow, 2nd Edition](https://mycuhk-my.sharepoint.com/:b:/g/personal/1005271920_link_cuhk_edu_hk/EbWPBuMdsw1AowPko8q62NIBLEe8q1FIg_DRmatm6hSydw?email=andykhwun%40gmail.com&e=jMCmHr) by _Aurélien Géron_. Password is required to access the book.

[2nd edition GitHub Site](https://github.com/ageron/handson-ml2)

3rd edition of the book has been published in October 2022.

[3rd edition GitHub Site](https://github.com/ageron/handson-ml3)

Dataset are available in the GitHub Site for the 1st edition of the book.

[1st edition GitHub Site](https://github.com/ageron/handson-ml)

The data can also be accessed using Python codes, which are available in the Jupiter Notebook samples.


## An Introduction to Statistical Learning with Applications in R

[An Introduction to Statistical Learning with Applications in R](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Machine-Learning/ISLRv2_corrected_June_2023.pdf) (2021, 2nd Edition) by _Gareth James_, _Daniela Witten_, _Trevor Hastie_, and _Robert Tibshirani_.

[Book website](https://www.statlearning.com/)

Data for the book has been downloaded and could be found in my [GitHub site](https://github.com/stevenkhwun/Online-resources/tree/main/ISLR).



## Introduction to Machine Learning with Python

[Introduction to Machine Learning with Python](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Machine-Learning/Introduction-to-Machine-Learning-with-Python.pdf) (2017) by _Andreas C. Müller_ and _Sarah Guido_.

Datasets and Jupyter Notebooks are available at the book's [GitHub site](https://github.com/amueller/introduction_to_ml_with_python).



## An R Companion for Introduction to Data Mining (2021)
*By Michael Hahsler*

This book contains documented R examples to accompany several chapters of the popular data mining textbook *Introduction to Data Mining* by *Pang-Ning Tan, Michael Steinbach, Anuj Karpatne and Vipin Kumar*. The companion book can be used with either edition: 1st edition (Tan, Steinbach, and Kumar 2005) or 2nd edition (Tan et al. 2017).

[Book website](https://mhahsler.github.io/Introduction_to_Data_Mining_R_Examples/book/)


## Practical Machine Learning with Python

[Practical Machine Learning with Python](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Machine-Learning/Practical-Machine-Learning-with-Python.pdf) (2018) by _Dipanjan Sarkar_, _Raghav Bali_ and _Tushar Sharma_.

Datasets and Jupyter Notebooks are available at the book's [GitHub site](https://github.com/dipanjanS/practical-machine-learning-with-python).


## Dive into Deep Learning

[Dive into Deep Learning](https://d2l.ai/index.html) by Aston Zhang, Zachary C. Lipton, Mu Li and [Alexander J. Smola](https://alex.smola.org/)


# Mathematical Analysis

## Basic Analysis: Introduction to Real Analysis
*By Jiří Lebl*

[Web version](https://www.jirka.org/ra/html/frontmatter-1.html)

[Book Website](https://www.jirka.org/ra/)

This free online textbook (OER more formally) is a course in undergraduate real analysis (somewhere it is called "advanced calculus"). The book is meant both for a basic course for students who do not necessarily wish to go to graduate school, but also as a more advanced course that also covers topics such as metric spaces and should prepare students for graduate study.

# Math and Statistics for Data Science

## Data Science and Machine Learning: Mathematical and Statistical Methods

[Data Science and Machine Learning: Mathematical and Statistical Methods](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Math-Stat-for-Data-Science/DSML_2023.10.30.pdf), 2023, by *Dirk P. Kroese, Zdravko I. Botev, Thomas Taimre, and Radislav Vaisman*.

More information about the book can be found in the official [Book Website](https://people.smp.uq.edu.au/DirkKroese/DSML/).

Data and codes are available at the [GitHub](https://github.com/DSML-book/) site.

## Mathematics for Machine Learning

[Mathematics for Machine Learning](https://nbviewer.org/github/mml-book/mml-book.github.io/blob/master/book/mml-book.pdf), 2024, by *Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong*. The above link is directly from the GitHub site of the book. The book is continually updated by the authors.

More information about the book can be found in the official [Book Website](https://mml-book.github.io/).

Data and codes are available at the [GitHub](https://github.com/mml-book/mml-book.github.io) site.


## Essential Math for Data Science 

[Essential Math for Data Science](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Math-Stat-for-Data-Science/Essential-Math-for-Data-Science.pdf) (2022) by _Thomas Nield_.

Supplemental material (code examples, exercises, etc.) is available for download at
https://github.com/thomasnield/machine-learning-demo-data.




# MATLAB

## Mastering MATLAB

***[Mastering MATLAB, 2012 Edition](http://www.masteringmatlab.com/)***


# Power BI

## Introduction to Power BI

These are the course notes for the “Introduction to Power BI” course given by the [Monash Bioinformatics Platform](https://www.monash.edu/researchinfrastructure/bioinformatics) for the [Monash Data Fluency](https://monashdatafluency.github.io/) initiative.

[Website](https://monashdatafluency.github.io/Power_BI/)

The PDF copy of the notes has been saved at the subfolder /PowerBI of this folder.


# Python

## Python for Data Analysis

This is the book website for the book ***[Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter](https://wesmckinney.com/book/)*** 3rd Edition by *Wes McKinney*. The book can be viewed online from this site. 

## Think Python

[Think Python](https://allendowney.github.io/ThinkPython/index.html#) (2022, 3rd edition) by _Allen B. Downey_.


## Intro to Python

[Intro to Python for Computer Science and Data Science](https://mycuhk-my.sharepoint.com/:b:/g/personal/1005271920_link_cuhk_edu_hk/Eciu-llFa-dJjgw6Mz0VdSYBSMz7AIy7iBA2Agu1nOvFSg?email=andykhwun%40gmail.com&e=8cZGhN) by *Paul Deitel* and *Harvey Deitel*. (Password required)

# R

## **R for Data Science (2e)**
*By Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund*

The book was published in June 2023 and its website can be found [here](https://r4ds.hadley.nz/). 

**Website and PDF copy of its 1st edition**

The first edition of the book, which was published in 2017, can be found [here](https://r4ds.had.co.nz/). The PDF copy of this book can be access in the following folder of the computer:

C:\\Library\\R\\Wickham_RFDS



## **Introduction to Data Science: Data Analysis and Prediction Algorithms with R**
*By Rafael A. Irizarry*


This book is now in the the second edition which is divided into two parts:

[Introduction to Data Science: Data Wrangling and Visualization with R](http://rafalab.dfci.harvard.edu/dsbook-part-1/).

[Advanced Data Science: Statistics and Prediction Algorithms Through Case Studies](http://rafalab.dfci.harvard.edu/dsbook-part-2/).


**Website and PDF copy of its 1st edition**

The first edition of the book can be found [here](http://rafalab.dfci.harvard.edu/dsbook/). The PDF copy of this book can be access in the following folder of the computer:

C:\\Library\\R\\Irizarry_ITDS




## **ggplot2: Elegant Graphics for Data Analysis (3e)**

This is the book website for the book ***[ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/)*** by *Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen*. The book can be viewed online.

## **R Markdown Cookbook**

This is the book website for the book ***[R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)*** by *Yihui Xie, Christophe Dervieux and Emily Riederer*. The book can be viewed online from this website.


## **psyTeachR**

[psyTeachR](https://psyteachr.github.io/): Great resource that provides a number of interactive books and tutorials for doing reproducible research in R. This website covers a broad range of topics on data cleaning, visualization, reproducible workflows, and more. From their website: "Our curriculum now emphasizes essential ‘data science’ graduate skills that have been overlooked in traditional approaches to teaching, including programming skills, data visualisation, data wrangling and reproducible reports. Students learn about probability and inference through data simulation as well as by working with real datasets.""


## **Learning R: 2019 Summer Workshop for NYU CDSC Lab**

[Learning R: 2019 Summer Workshop for NYU CDSC Lab](https://nyu-cdsc.github.io/learningr/)

This website contains some textbooks in R.

# Statistics

## Practical Statistics for Data Scientists

[Practical Statistics for Data Scientists: 50+ Essential Concepts Using R and Python](https://nbviewer.org/github/stevenkhwun/Online-resources/blob/main/Books_Handbooks_Notes/Statistics/PracticalStatisticsforDataScientists.pdf) by *Peter Bruce, Andrew Bruce & Peter Gedeck*.